// data.js
// Base de dados da auditoria de SGQ (Sistema de Gestão da Qualidade)
// Cada requisito recebe, além dos campos originais, os campos:
// responsavel, local, evidencias e status (Conforme | Não Aplicável | Não Conforme)

const auditoria = [
  {
    requisito: "4.1",
    titulo: "Requisitos gerais",
    departamento: "Qualidade",
    pontosVerificacao: [
      "Processos do SGQ identificados e sequenciados",
      "Resultados dos processos monitorados",
      "Ações de melhoria contínua implementadas",
      "Processos terceirizados sob controle",
    ],
    status: null, // "conforme" | "nao-conforme" | "nao-aplicavel"
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "4.2",
    titulo: "Requisitos de documentação",
    departamento: "Qualidade",
    pontosVerificacao: [
      "Política e objetivos da qualidade documentados",
      "Manual da Qualidade existente e completo",
      "Procedimentos documentados (controle de documentos, registros, NC, etc.)",
      "Controle de registros da empresa",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "5.1",
    titulo: "Comprometimento da direção",
    departamento: "Direção",
    pontosVerificacao: [
      "Comunicação da importância dos requisitos legais/clientes",
      "Política de qualidade definida",
      "Recursos garantidos pela direção",
      "Objetivos e indicadores monitorados",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "5.3",
    titulo: "Política da qualidade",
    departamento: "Direção",
    pontosVerificacao: [
      "Política divulgada a colaboradores e subcontratados",
      "Análise periódica de adequação da política",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "6.2",
    titulo: "Recursos humanos",
    departamento: "Recursos Humanos",
    pontosVerificacao: [
      "Conscientização dos colaboradores sobre suas atividades",
      "Competências necessárias definidas",
      "Registros de escolaridade, qualificação e treinamento",
      "Eficácia das ações de capacitação avaliada",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "7.2",
    titulo: "Processos relacionados ao cliente",
    departamento: "Comercial",
    pontosVerificacao: [
      "Requisitos da obra determinados (cliente, legais, técnicos)",
      "Análise dos requisitos registrada",
      "Alterações de requisitos controladas",
      "Comunicação com o cliente durante a obra",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "7.4",
    titulo: "Aquisição",
    departamento: "Comercial",
    pontosVerificacao: [
      "Fornecedores qualificados e avaliados",
      "Informações de compra controladas",
      "Inspeção de materiais e serviços adquiridos",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "7.5",
    titulo: "Operações de produção e fornecimento de serviço",
    departamento: "Produção / Obra",
    pontosVerificacao: [
      "Procedimentos executivos documentados e disponíveis na obra",
      "Monitoramento e medição dos produtos executados",
      "Rastreabilidade de materiais especiais",
      "Preservação da conformidade dos serviços executados",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "8.3",
    titulo: "Controle de materiais e serviços não-conformes",
    departamento: "Inspeção",
    pontosVerificacao: [
      "Procedimento documentado para produto não-conforme",
      "Registros de tratamento de não-conformidades",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
  {
    requisito: "8.5",
    titulo: "Melhoria",
    departamento: "Administrativo",
    pontosVerificacao: [
      "Ações corretivas para eliminar causas de não-conformidade",
      "Ações preventivas para evitar problemas potenciais",
      "Melhoria contínua da eficácia do SGQ",
    ],
    status: null,
    responsavel: "",
    local: "",
    evidencias: "",
  },
];
